platform :ios do
    lane :release do
        build(type: 'appstore')
    end

    lane :development do
        build(type: 'development')
    end

    lane :build do |options|
        remove_platform()
        match(
            type: options[:type],
            readonly: true
        )
        sh 'cordova platform add ios'
        # Apologies for this nastiness, but 'cordova' fastlane plugin doesn't seem to work and we need to 'build' rather than 'prepare''
        # otherwise the status bar plugin doesn't to get loaded
        sh 'cordova build ios || true'
        sh 'open ../platforms/ios/honesty.store.xcworkspace'
    end

    lane :remove_platform do
        sh 'cordova platform rm ios'
        sh 'rm -rf ../plugins/*'
    end;
end
